---

  # Configurações de intervalos de tempo
  time_intervals:
    
    # Intervalo de tempo para verificar se há heróis disponíveis para trabalhar
    # Valor padrão (em minutos): 10
    send_heroes_for_work: 10
    
    # Intervalo de tempo para atualizar a posição dos heróis no mapa
    # Valor padrão (em minutos): 3
    refresh_heroes_positions: 5
    
    # Intervalo de tempo para verificar por novos mapas
    # Valor padrão (em segundos): 5
    check_for_new_map_button: 2
    
    # Intervalo de tempo para verificar se existe solicitação de ‘login’
    # Valor padrão (em minutos): 5
    check_for_login: 1

    # Intervalo de tempo entre movimentos
    # Valor padrão (em segundos): 1
    interval_between_movements: 1
    
    # Intervalo de tempo para verificar se o saldo aumentou
    # Valor padrão (em minutos): 60
    get_balance: 60

    # Intervalo de tempo para atualizar a página
    # Valor padrão (em minutos): 30
    check_for_refresh_page: 30

  # O quão confiante o Bot. precisa estar para clicar nos botões (valores entre 0 e 1. Onde 0 é o valor mínimo, 1 é o valor máximo)
  threshold:
    # Valor padrão: 0.7
    default: 0.7

    # Valor padrão: 0.8
    common: 0.8

    # Valor padrão: 0.8
    rare: 0.8

    # Valor padrão: 0.8
    super_rare: 0.8
        
    # Valor padrão: 0.8
    epic: 0.8
    
    # Valor padrão: 0.8
    legend: 0.8    
    
    # Valor padrão: 0.8
    super_legend: 0.8      
    
    # Valor padrão: 0.8
    select_wallet_buttons: 0.8

    # Valor padrão: 0.9
    go_to_work_btn: 0.9
    
    # Valor padrão: 0.7
    bau_roxo: 0.7

    # Valor padrão: 0.8
    bau_roxo_50: 0.8

    # Valor padrão: 0.7
    bau_gold: 0.7

    # Valor padrão: 0.8
    bau_gold_50: 0.8

    # Valor padrão: 0.7
    bau_blue: 0.7

    # Valor padrão: 0.8
    bau_blue_50: 0.8

    # Valor padrão: 0.9
    green_bar: 0.9

  # Configurações do modo casa
  home:
    enable: False
    # Se o bot está enviando o hero errado para a home, aumente esse número.
    # Se o bot não está enviando o hero, diminua esse número.
    hero_threshold: 0.8
    home_button_threshold: 0.9


  # Valor padrão: 60
  scroll_size: 60

  # Valor padrão: 5
  scroll_attempts: 5

  # Valor padrão: true
  use_click_and_drag_instead_of_scroll: true

  # Valor padrão: 200
  click_and_drag_amount: 200

  # Valor padrão: green
  # all = utiliza o comando enviar todos
  # green = seleciona os heróis com a barra de stamina verde (metade ou cheia)
  # full = seleciona somente os heróis com a barra de stamina cheia
  select_heroes_mode: "green"

  # Opção para salvar os logs em arquivo (logs.txt)
  # Valor padrão: False
  # Opções disponíveis: False ou True
  save_log_to_file: True
